export const footerData = {
  footer_title: {
    title_ua: 'Контакти',
    title_ru: 'Контакты',
    title_en: 'Contacts',
    upButton_ua: 'вгору',
    upButton_ru: 'вверх',
    upButton_en: 'up',
  },
  copy: {
    title_ua: '2021 "Шо? School" © Всі права захищені.',
    title_ru: '2021 "Шо? School" © Все права защищены.',
  },
  menu: {
    home_ua: 'Головна',
    home_ru: 'Главная',
    home_en: 'Home',
    order_ua: 'На замовлення',
    order_ru: 'Под заказ',
    order_en: 'In order',
    catalog_ua: 'Готові меблі',
    catalog_ru: 'Готовая мебель',
    catalog_en: 'Finished furniture',
    about_ua: 'Про нас',
    about_ru: 'О нас',
    about_en: 'About us',
    galery_ua: 'Дизайнерам',
    galery_ru: 'Дизайнерам',
    galery_en: 'Designers',
    contacts_ua: 'Контакти',
    contacts_ru: 'Контакты',
    contacts_en: 'Contacts',
  },
  links: {
    confidentiality_ua: 'Політика конфіденційності',
    confidentiality_ru: 'Политика конфиденциальности',
    confidentiality_en: 'Privacy policy',
    link_confidentiality: '/privacy-policy/',
    contract_ua: 'Угода Користувача',
    contract_ru: 'Пользовательское соглашение',
    contract_en: 'User Agreement',
    link_contract: '/terms-of-use/',
    copy_ua: '© Ricchezza. Всі права захищені 2022.',
    copy_ru: '© Ricchezza. Все права защищены 2022.',
    copy_en: '© Ricchezza. All rights reserved 2022.',
  }
};
