export const homeData = {
  home_main: {
    top_ua: 'Засновано',
    top_ru: 'основаны',
    top_en: 'founded',
    title_ua: 'Ricchezza \nСтудія Дизайну \nМеблів',
    title_ru: 'Ricchezza \nСтудия Дизайна \nМебели',
    title_en: 'Ricchezza \nfurniture design \nstudio',
    description_ua: 'Завдяки індивідуальному підходу, \nми створюємо меблі любої складності, \nта на любий смак',
    description_ru: 'Благодаря индивидуальному подходу, \nмы создаем мебель любой сложности, \nи на любой вкус',
    description_en: 'Thanks to an individual approach, \nnwe create furniture of any complexity, \nand for every taste',
  },
  home_order: {
    description_ua: 'Меблі на замовлення',
    description_ru: 'Мебель на заказ',
    description_en: 'furniture for order',
    title_ua: 'НАШІ МАЙСТРИ СТВОРЮЮТЬ ДЛЯ ВАС СПРАВЖНІ ШЕДЕВРИ',
    title_ru: 'наши мастера создают для вас настоящие шедевры',
    title_en: 'OUR MASTERS CREATE TRUE MASTERPIECES FOR YOU',
    button_ua: 'Замовити меблі',
    button_ru: 'Заказать мель',
    button_en: 'order furniture',
    },
  home_benefits: {
    description_ua: 'Чому ми',
    description_ru: 'почему мы',
    description_en: 'furniture for order',
    title_ua: 'Ми завжди працюємо над підвищенням якості наших меблів та сервісу',
    title_ru: 'Мы всегда работаем над повышением качества наших мебели и сервиса',
    title_en: 'We are always working to improve the quality of our furniture and service',
    benefits: [
      {
        title_ua: 'Вишуканість дизайну \nнаших меблів',
        title_ru: 'Изысканность дизайна \nнашей мебели',
        title_en: 'oThe sophistication of \nour furniture design',
      },
      {
        title_ua: 'Висока якість та надійність \nусіх виробів',
        title_ru: 'Высокое качество и надежность \nвсех изделий',
        title_en: 'High quality and reliability \nof all products',
      },
      {
        title_ua: 'Екологічність та \nнатуральність матеріалів',
        title_ru: 'Экологичность и \nнатуральность материалов',
        title_en: 'Environmental friendliness and \nnaturalness of materials',
      },
      {
        title_ua: 'Доставка готової \nпродукції по всій країні',
        title_ru: 'доставка готовой \nпродукции по всей стране',
        title_en: 'delivery of finished \nproducts throughout the country',
      },
    ]
  },
  home_catalog: {
    description_ua: 'Каталог готових меблів',
    description_ru: 'Каталог готовой мебели',
    description_en: 'Finished furniture catalog',
    title_ua: 'В нашому каталозі ви зможете обрати готві меблі на різноманітний смак',
    title_ru: 'В нашем каталоге вы сможете выбрать готовую мебель на разнообразный вкус.',
    title_en: 'In our catalog you can choose ready-made furniture for different tastes',
    button_ua: 'Перейти в каталог',
    button_ru: 'Перейти в каталог',
    button_en: 'go to catalog',
    catalog: {
      title_ua: 'Стіл “Futuristic”',
      title_ru: 'Стол “Futuristic”',
      title_en: 'Table "Futuristic"',
      price: '12 000',
      link: '/product-card/',
    },
 },
  home_video: {
    video: 'https://youtu.be/sDeMfL8Ib9A',
    cover: 'cover',
  },
  home_about: {
    description_ua: 'Про студію “Ricchezza”',
    description_ru: 'О студии "Ricchezza"',
    description_en: 'About Ricchezza Studio',
    title_ua: 'Студія “Ricchezza” виробник меблів Європейського рівня та якості',
    title_ru: 'Студия "Ricchezza" производитель мебели Европейского уровня и качества',
    title_en: 'Ricchezza Studio is a manufacturer of furniture of European level and quality',
    image_info: {
      title_ua: '8 років',
      title_ru: '8 лет',
      title_en: '8 years',
      description_ua: 'Ми створюємо для вас \nзатишок та комфорт',
      description_ru: 'Мы создаем для вас \nуют и комфорт',
      description_en: 'We will let you \ncalm down and comfort',
    },
    about_info: [
      {
        marker_ua: 'Хто ми:',
        marker_ru: 'Кто мы:',
        marker_en: 'Who we are:',
        description_ua: 'Нец ет ерос тота яуодси, ферри иусто еум ин, инани иудицабит яуаерендум хас ан. Лорем ипсум долор сит амет, доценди пондерум ид при, проприае пхаедрум вих еа. Сед деленити сенсибус адверсариум еу, еи оратио аудире хис, еос принципес сцрипторем ад.',
        description_ru: 'Нец эт ерос тота яуодсы, ферри иусто еум ин, инаны иудицабит яуаэрендум хас ан. Лорем ипсум долор сит амет, доценды пондерум ид при, проприает пхаэдрум их еа. Сед разделить сенсибус адверсариум еу, еи оратио аудире хис, еос принципес сцриптором ад.',
        description_en: 'Net et eros tota yauodsi, ferri iusto eum in, inani iuditsabit yawaerendum has an. Lorem ipsum dolor sit amet, docendi ponderum id pri, propriee phaedrum vih ea. Sed deleniti sensibus adversarium eu, ei oratio audire his, eos principes scriptorem ad.',
      },
      {
        marker_ua: 'Наша історія:',
        marker_ru: 'Наша история:',
        marker_en: 'Our story:',
        description_ua: 'Нец ет ерос тота яуодси, ферри иусто еум ин, инани иудицабит яуаерендум хас ан. Лорем ипсум долор сит амет, доценди пондерум ид при, проприае пхаедрум вих еа. Сед деленити сенсибус адверсариум еу, еи оратио аудире хис, еос принципес сцрипторем ад.',
        description_ru: 'Нец эт ерос тота яуодсы, ферри иусто еум ин, инаны иудицабит яуаэрендум хас ан. Лорем ипсум долор сит амет, доценды пондерум ид при, проприает пхаэдрум их еа. Сед разделить сенсибус адверсариум еу, еи оратио аудире хис, еос принципес сцриптором ад.',
        description_en: 'Net et eros tota yauodsi, ferri iusto eum in, inani iuditsabit yawaerendum has an. Lorem ipsum dolor sit amet, docendi ponderum id pri, propriee phaedrum vih ea. Sed deleniti sensibus adversarium eu, ei oratio audire his, eos principes scriptorem ad.',
      },
    ],
  },
  home_partners: {
    description_ua: 'Наші партнери',
    description_ru: 'Наши партнеры',
    description_en: 'Our partners',
    title_ua: 'Ми раді співпрацювати з \nвідомими брендами',
    title_ru: 'Мы рады сотрудничать с \nизвестными брендами',
    title_en: 'We are happy to cooperate with \nfamous brands',
    button_ua: 'Більше про студію',
    button_ru: 'Больше о студии',
    button_en: 'More about the studio',
  },
  home_steps: {
    description_ua: 'До створення меблів \nвашої мрії',
    description_ru: 'К созданию мебели \nвашей мечты',
    description_en: 'To create the furniture of \nyour dreams',
    title_ua: '4 кроки',
    title_ru: '4 шага',
    title_en: '4 steps',
    steps_info: [
      {
        title_ua: 'Вибір продукту та вибір \nстилю меблів',
        title_ru: 'Выбор продукта и выбор \nстиля мебели',
        title_en: 'Product selection and \nfurniture style selection',
      },
      {
        title_ua: 'Договір та розрахунок \nпроекту',
        title_ru: 'Договор и расчет \nпроекта',
        title_en: 'Contract and project \ncalculation', 
      },
      {
        title_ua: 'Креслення та \nтехнологічна частина',
        title_ru: 'Чертеж и \nтехнологическая часть',
        title_en: 'Drawings and \ntechnological part',
      },
      {
        title_ua: 'Доставка та монтаж \nготових меблів',
        title_ru: 'Доставка и монтаж \nготовой мебели',
        title_en: 'Delivery and installation of \nfinished furniture',
      },
    ],
    
  },
  home_galery: {
    description_ua: 'Наші останні роботи',
    description_ru: 'Наши последние работы',
    description_en: 'Our latest work',
    title_ua: 'Усі наші проекти та вироби створено для вас з любов’ю',
    title_ru: 'Все наши проекты и изделия созданы для вас с любовью',
    title_en: 'All our projects and products are created for you with love',
    catalogButton_ua: 'Перейти в каталог',
    catalogButton_ru: 'Перейти в каталог',
    catalogButton_en: 'Go to the directory',
    orderButton_ua: 'Замовити меблі зараз',
    orderButton_ru: 'Заказать мебель сейчас',
    orderButton_en: 'Order furniture now',
  },
};

